### ISSUE TITLE
请问现在可以自己搭建出块的测试节点吗

### ISSUE THREAD

**Issue by Sirormy** [HuobiGroup/huobi-chain#136]
目前测试节点已经运行，并在同步数据，如果要作为出块节点需要哪些操作和条件？谢谢。

**Comment by LycrusHamster** [comment]
Greetings Siromy

I am not so much clear about the running environment of your business. Is that running 'test' node kicked-up by you as private chain? Sync-ing data need More than 2 running nodes, how many nodes are running?

Well, generally, the consensus is configed in services.metadata.verifier_list field of genesis.toml.
Please refer the below link to get more info.

[link](https://docs.muta.dev/docs/setup/genesis-config/)

Shortly, the block-producing/mining node should be set into metadata and can be modified in runtime.
here is a part from the example of the link before:

[[services]]
name = "metadata"
payload = '''
{
    "chain_id": "0xb6a4d7da21443f5e816e8700eea87610e6d769657d6b8ec73028457bf2ca4036",
    "bech32_address_hrp": "muta",
    "common_ref": "0x703873635a6b51513451",
    "timeout_gap": 99999,
    "cycles_limit": 999999999999,
    "cycles_price": 1,
    "interval": 3000,
    "verifier_list": [
       {
           "bls_pub_key": "0x04102947214862a503c73904deb5818298a186d68c7907bb609583192a7de6331493835e5b8281f4d9ee705537c0e765580e06f86ddce5867812fceb42eecefd209f0eddd0389d6b7b0100f00fb119ef9ab23826c6ea09aadcc76fa6cea6a32724",
           "pub_key": "0x02ef0cb0d7bc6c18b4bea1f5908d9106522b35ab3c399369605d4242525bda7e60",
           "address": "muta14e0lmgck835vm2dfm0w3ckv6svmez8fdgdl705",
           "propose_weight": 1,
           "vote_weight": 1
       }
    ],
    "propose_ratio": 15,
    "prevote_ratio": 10,
    "precommit_ratio": 10,
    "brake_ratio": 7,
    "tx_num_limit": 9000,
    "max_tx_size": 10485760
}
'''

verifier_list is the committee which is usually known as set of mining nodes.
bls_pub_key and pub_key are the public keys of cryptographich in order to verify the signatures.
propose_weight and vote_weight are the weight of power used in consensus. you can set them all to 1 as default.
and you can leave the rest as default.

node that, bech32_address_hrp is the human readable prefix of the address, please check it carefully and set for your business.
also node the secret/private key is configed in chain.toml by 'privkey' field, all mentioned cryptographic settings must match!

to keep/discover connectivity via p2p network as I mentioned there have to be more than 2 nodes to reach consensus and sync, you had better tell the bootstrap node address by 'network.bootstraps' field in chain.toml.

all the infomation you may need could be generated from 'keypair' tools,
here is the code [keypair](https://github.com/nervosnetwork/muta/blob/master/devtools/keypair/src/main.rs).
I guess you have to build it and run by your self.

Sincerely looking forward for you reply.

Best Regards
